---
# CentOS specific package installations
- include: RedHat.yml
  when: ansible_os_family  == "RedHat"

# Ubuntu specific package installations
- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: check if GPG key is present
  command: bash -c "gpg -k | grep D39DC0E3"
  ignore_errors: true
  register: result

# Add an apt key by id from a keyserver
- name: Import GPG keys
  command: 'gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3'
  changed_when: False
  when: result|failed

- name: check if RVM is installed
  command: bash -c "source /usr/local/rvm/scripts/rvm && rvm"
  ignore_errors: true
  register: result
  sudo: yes

- name: install RVM
  command: bash -c "curl -L https://get.rvm.io | bash -s stable"
  sudo: yes
  when: result|failed

- name: install Ruby
  command: bash -c "source /usr/local/rvm/scripts/rvm && rvm install ruby"
  sudo: yes

- name: add source rvm for all users
  copy: src=rvm-env.sh
        dest=/etc/profile.d/rvm-env.sh
        owner=root
        group=root
        mode=0644

- name: set a default Ruby
  command: bash -c "source /usr/local/rvm/scripts/rvm && rvm use ruby --default"
  sudo: yes

- name: check if eye is installed
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye i"
  register: result
  ignore_errors: yes

- name: install eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && gem install eye"
  sudo: yes
  when: result|failed

# - name: install eye
#   command: bash -c "source /usr/local/rvm/scripts/rvm && gem install eye"
#   sudo: no

- name: create eye config dir
  file: state=directory path=/etc/eye owner=root group=root mode=0755

- name: create eye log dir
  file: state=directory path=/var/log/eye owner=root group=root mode=0755

- name: put eye definition to upstart configs
  template: src=eye.conf dest=/etc/init/eye.conf owner=root group=root mode=0644
  when: ansible_distribution == "Ubuntu"

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l /etc/eye/apps.eye"
  sudo: yes
