---
# CentOS specific package installations
- include: RedHat.yml
  when: ansible_os_family  == "RedHat"

# Ubuntu specific package installations
- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: check if eye is installed
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye i"
  register: result
  changed_when: result.rc > 0
  failed_when: no

- name: install gmp
  apt: name=libgmp-dev state=present

- name: install eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && gem install eye"
  sudo: yes
  when: result.rc > 0

- name: create eye log dir
  file: state=directory path=/var/log/eye{{ '-' + eye_user if eye_user != 'root' else '' }} owner={{ eye_user }} group={{ eye_user }} mode=0777

- name: setup logrotate for eye
  template: src=logrotate.d/eye dest=/etc/logrotate.d/eye{{ '-' + eye_user if eye_user != 'root' else '' }}
  register: result

- name: logrotate
  shell: logrotate /etc/logrotate.d/eye{{ '-' + eye_user if eye_user != 'root' else '' }}
  when: result.changed

- name: put eye definition to upstart configs
  template: src=eye.conf dest=/etc/init/eye{{ '-' + eye_user if eye_user != 'root' else '' }}.conf owner=root group=root mode=0644
  when: ansible_distribution == "Ubuntu"

- name: load config in eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l {{ eye_home }}/apps.eye"
  sudo: yes
  sudo_user: "{{ eye_user }}"

- name: put eye bin
  template: src=eye dest=/usr/local/bin/eye mode=755
