---
- name: ensure eye_user is presented
  user: name={{ eye_user }} shell=/bin/bash

- name: get user's home
  command: bash -c 'eval echo "~{{ eye_user }}"'
  when: eye_user != 'root'
  changed_when: false
  register: eye_user_home
#"

- name: define eye home
  set_fact:
    eye_home: /etc/eye
  when: eye_user == 'root'
  tags: always

- name: define eye home
  set_fact:
    eye_home: "{{ eye_user_home.stdout }}/eye"
  when: eye_user != 'root'
  tags: always

- name: create eye config dir
  file: state=directory path={{ eye_home }} owner={{ eye_user }} group={{ eye_user }} mode=0755

- name: put apps.rb eye config file
  template: src=apps.rb dest={{ eye_home }}/apps.eye owner={{ eye_user }} group={{ eye_user }} mode=0644

- include: eye.yml

- include: remove.yml
  when: eye_remove