- name: remove eye config dir
  file: state=absent path={{ eye_home }}

- name: remove eye definition to upstart configs
  file: state=absent path=/etc/init/eye{{ '-' + eye_user if eye_user != 'root' else '' }}.conf
  when: ansible_distribution == "Ubuntu"

- name: remove eye log dir
  file: state=absent path=/var/log/eye{{ '-' + eye_user if eye_user != 'root' else '' }}

- name: remove depricated eye log for root
  file: state=absent path=/var/log/eye.log 
  
- name: quit eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye q"
  become: yes
  become_user: "{{ eye_user }}"
