---
- name: reload eye configs
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l {{ eye_home }}/apps.eye"
  become: yes
  become_user: "{{ eye_user }}"

- name: reload eye
  command: bash -c "source /usr/local/rvm/scripts/rvm && eye l {{ eye_home }}/apps.eye"
  become: yes
  become_user: "{{ eye_user }}"
